### ISSUE TITLE
Show that Creators list on Contact form is scrollable

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/portal-ui#1263]
There is some confusion with the Creators list on the Collection form.  When the list is longer than the display box it isn't obvious that there are more entries that can be scrolled to because there is no visible scroll bar and the last entry in the list perfectly aligns with the bottom of the box.

**Comment by mccalluc** [comment]
@tsliaw : Thinking about this, I've had the same problem with the metadata box... It looks like there is some CSS that can bring the system scroll bars back, or you might have other ideas about how to communicate that a section can scroll... maybe even just a small adjustment to the height, so that a row is clearly cut in half?
