### ISSUE TITLE
What does it look like if an API isn't happy?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1299]
Follow up to #1189: https://gateway.api.hubmapconsortium.org/status.json is great, but what does it look like if a single API is down? missing key? or just empty? or the whole thing fails? or...?

**Comment by yuanzhou** [comment]
The assumption is the Gateway service is always running since it handles all the authentication and authorization checks for requests to all other API services. That's why the Gateway json section only shows `version` and `build` information. 

For all other API services, they all have the `api_auth` key with a boolean value. When a single API happens to be down, you'll see the `api_auth` of that API json section to be `false`, meaning the Gateway can't do the auth check for that API.

**Comment by mccalluc** [comment]
Thanks!
