### ISSUE TITLE
Evaluate improvements suggested by Google Lighthouse

### ISSUE THREAD

**Issue by john-conroy** [hubmapconsortium/portal-ui#1358]
We're on track with #1349, and soon #711 and #1348, but we should better evaluate suggestions from Google Lighthouse to see if we can further improve performance.

**Comment by mccalluc** [comment]
After those are deployed, John will look at it again and see if any other work is needed.

**Comment by mccalluc** [comment]
Current scores (Desktop):

homepage:
```
Performance: 91
Accessiblity: 87
Best Practices: 100
SEO: 82
```
datasets search:
```
Performance: 75
Accessibility: 87
Best Practices: 100
SEO: 80
```
[details](https://portal.hubmapconsortium.org/browse/dataset/f9ae931b8b49252f150d7f8bf1d2d13f):
```
Performance: 46
Accessibility: 81
Best Practices: 93
SEO: 90
```

Right now, I'm going to review the reports and file issues for the sore points, and will mention "Lighthouse" in the subject line. @john-conroy: I think this only stayed open because I wanted to loop back after some of your fixes were implemented. Closing, but feel free to re-open if you think that's premature.
