### ISSUE TITLE
Update docs menu

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1966]
The current menu is:
- Overview
- Software
- FAQ
- About

@computationdoc says:
> top level Documentation menu only would have three items in new set up: 
> - the new Documentation submenu, 
> - the current FAQ submenu,
> - the current About submenu

Questions:
- By "Documentation submenu", do you mean mean ["Technical"](https://portal.hubmapconsortium.org/docs/technical)?
- Should the current ["Overview"](https://portal.hubmapconsortium.org/docs) page be removed?

**Comment by computationdoc** [comment]
Thank you Chuck:

Answers:

What I understood was agreed was :
Documentation
	Documentation
	FAQ
	About

Above decision, while duplicating Documentation, is most correct because the new Document needed, per NIH, and others, to include the policy not just the technical, and the prior information in Overview was added in that one markdown now too as I understand 

If you, as “designer” or “ultimate arbitrator” after reading the document strongly felt Documentation should not be both menu and menu-item to be consistent with your portal design and coherence then I’m totally fine as requestor with the menu-item to be Technical

Yes, the Overview page is to be removed because as noted above that information was intentionally included in a single master documentation page - so there is just the three in final form.

Thank you!

JCS

**Comment by computationdoc** [comment]
For consistency I note: if the Menu-item is Technical Documentation or Technical or Documentation then the first large title in the markdown of that document should probably be updated to same also - thank you.

JCS

**Comment by computationdoc** [comment]
Sorry if there is an confusion - the MarkDown top level title is currently HuBMAP Documentation so the NEW menu-item (replacing Overview and Software) is "ideally" HuBMAP Documentation so:
Documentation
     HuBMAP Documentation
     FAQ
     About

may be ideal
