### ISSUE TITLE
Show globus links for derived datasets

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1972]
Links to globus for derived, vis-lifted dataset should be made available. Initial proposal (but wait for final wording from @ngehlenborg )
```diff
Files are available through the Globus Research Data Management System. 
Access dataset HBM423.JZTB.864 on Globus.
+ Access derived dataset HBM123.ABCD.456 on Globus
```
Maybe "Support"? That's how they are described it in the UI.

Question: Would it be ok if this was done for _all_ derived data sets, rather than depending on the vis lifting logic? 

_Originally posted by @mccalluc in https://github.com/hubmapconsortium/portal-ui/issues/1947#issuecomment-869841428_

**Comment by ngehlenborg** [comment]
We should only add the text and link for datasets that are using vis-lifting because there is no other way to get to the data used by Vitessce otherwise. In the general case, derived datasets have a Globus link (+ directory listing) available on the corresponding dataset page.

I propose the following language: 
```diff
Files are available through the Globus Research Data Management System. 
Access dataset HBM423.JZTB.864 on Globus.
+ Data generated for visualization of this dataset are in support dataset HBM123.ABCD.456 on Globus.
```
