### ISSUE TITLE
Endpoints to grab Donor/Sample/Dataset metadata

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2039]
Using the APIs is hard: people just want a TSV of the metadata. 

Proposal:
- `/api/v1/donors.tsv`, `/api/v1/samples.tsv`, `/api/v1/datasets.tsv`
- In addition to the "metadata" include IDs, creation date, creator.
- Order of columns will be arbitrary.
- Sorting will be arbitrary.
- column names can be the internal, ugly, ES, names.
- If logged in, more will be returned.
- Document this API.

@ngehlenborg : Look good? In particular:
- There are a lot of fields beyond the "metadata"... Do you just want IDs, creation date, creator... or would you like more? What about metadata from ancestor entities?
- If it's easier for people to ask us to re-implement the existing APIs, rather than using what's out there, then part of the problem may be documentation... So it follows that we should document our nascent API at least as well as the real APIs are documented.
- Bill should be told about this, at least so their API docs can be updated to point at the easy-to-use APIs we're implementing.

**Comment by ngehlenborg** [comment]
Thank you. A few quick comments:

* Column order can be arbitrary but IDs should preferably come first (HuBMAP ID, UUID, and then all the rest).
* What do the internal ES column names look like? Things like `sequencing_read_percent_q30` are perfectly fine.
* I assume you mean that more rows will be returned for users who are logged in. Please correct me if I got that wrong.
* Due to the presence of multiple ancestors for many datasets, I would suggest ancestor metadata only for samples for now. My opinion might change if we see that not having ancestor metadata greatly reduces value of the dataset metadata table.
* Documentation wins, always 🥇
