### ISSUE TITLE
search-api will give us 401s when token expires

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#208]
Bill Shirey  4:57 PM
Maybe you have an old/expired/revoked token?

Zhou (Joe) Yuan  4:58 PM
@Chuck McCallum that's probably one of the bugs I fixed in the new release. But because the new release breaks portal-ui, I'll fix it separately and Bill and I have discussed the short-term solution.

Bill Shirey  4:58 PM
The 500 error was what Zhou was trying to fix in the release that was backed out today.

Zhou (Joe) Yuan  5:02 PM
@Chuck McCallum here is the short-term solution that Bill and I discussed: the search-api will pass through all queries to elasticsearch as long as the token is valid and the user belongs to the HuBMAP read group on globus. But if the token is invalid, expired, or missing from the request header, the search-api will throw back 401 error.
5:03
I'll also include the fix to that 500 error into this new solution.
5:03
Nothing needs to be changed on portal-ui, except you wanted to handle the 401 with some user-friendly messages.

**Comment by yuanzhou** [comment]
In addition to 401, it's possible to get back 403 as well. 

Due to data access restriction, indexed entries are protected and calls to the above endpoint require the `Authorization` header with the Bearer token (globus nexus token) along with the search query JSON body. There are three cases when making a search call:
Case 1: Missing/invalid/expired token
If a token is missing, invalid or expired, an error message with 401 status code will be returned.

Case 2: Valid token without the right group access
In the case that the token is valid BUT the owner of this token doesn't have the right group access, a 403 error message will be returned.

Case 3: Valid token with right group access
With a valid token (that represents a user who has the correct group access to the indexed data), ALL the user specified search query DSL (Domain Specific Language) detail will be passed to the Elasticsearch just like making queries against the Elasticsearch directly, and the search hits results will be returned. Elasticsearch will also return any error messges if the JSON query is misformatted.

**Comment by yuanzhou** [comment]
I think with this short-term fix/improvement, as long as the token is valid and represents a user who belongs to the HuBMAP read group, the portal-ui could send whatever query to the backend elasticsearch via the Search API.

The long-term goal would be supporting more access groups and add index parameter to the URL path. That would require some changes to the portal-ui's search workflow. For example, the API consumer sends a call to search-api first with a token, and we return a list of indices that can be accessed by that token. This is done by search-api talking to elasticsearch to get the all the indices first, then based on the token we call globus to get a list of groups that user is associated with. Then filter out the target indices. The second call from the user goes to search-api with the comma-separated indices in the URL path along with whatever JSON query/aggregations, we just pass through. That'll be much better than modifying the JSON

**Comment by mccalluc** [comment]
@yuanzhou : I haven't heard any complaints about this in a year. I'm assuming it's either been fixed, or such a rare edge case that we shouldn't spend time on it.

Please reopen if I'm mistaken.
