### ISSUE TITLE
Cells UI should distinguish NA from no-results

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2623]
Some genes just aren't covered by some results: The UI should be different, so users don't waste time trying to lower the bounds on their query.

Probably just an info box where the results would go?

**Comment by mccalluc** [comment]
probably duplicate of #2124? close if still not clear.

**Comment by tsliaw** [comment]
I think the difference from #2124 is this issue covers if it is more on the "user error" side (so if user's parameters doesn't provide a sufficient enough query) vs. that issue is more if we don't have enough data on our end to provide a sufficient query? This seems like the same thing at the end of the day, so will close for now.
