### ISSUE TITLE
AnnData versioning problem

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2693]
I don't know any other details. @ilan-gold or @jswelling -- Please fill this in to make it actionable. Or if in-person discussion is needed, please get it on a meeting agenda. Or sort it out on slack without me. Thanks.

**Comment by jswelling** [comment]
The nature of the problem is believed to be that the version of AnnData used by the azimuth-annotate container is writing AnnData files in a format which cannot be parsed by the downstream h5ad-to-arrow container.  This breaks the hand-off of the workflow between the two containers, and affects all RNAseq workflows run with the current azimuth-annotate main HEAD (c0d902d, 'add lung') .  My recollection is that this is a minor version change within AnnData version 0.7.  Vitessce cannot read AnnData files generated with the most recent versions, 0.8, so a full upgrade to the most recent AnnData is not feasible.

**Comment by mccalluc** [comment]
Thanks: I've found a corresponding issue for vitessce:
- https://github.com/vitessce/vitessce/issues/1186

I'll reach out on slack to see what the timeline is.

**Comment by mccalluc** [comment]
On Slack, @keller-mark volunteered:
> It wasn't assigned to anyone in particular but I can work on it now. I think it will entail using the properties encoding-type and encoding-version in the .zattrs [files](https://github.com/scverse/anndata/blob/master/docs/fileformat-prose.rst) of the AnnData-Zarr stores and then calling different functions in the [loader classes](https://github.com/vitessce/vitessce/tree/main/src/loaders/anndata-loaders) to load the data accordingly (and we will need to write new loader functions to support the encoding-versions added in v0.8)

**Comment by keller-mark** [comment]
> The nature of the problem is believed to be that the version of AnnData used by the azimuth-annotate container is writing AnnData files in a format which cannot be parsed by the downstream h5ad-to-arrow container

According to the [AnnData docs](https://github.com/scverse/anndata/blob/0.8.x/docs/fileformat-prose.rst), the anndata v0.8 package __can__ read files produced by the v0.7 package:

> These docs are written for anndata 0.8. Files written before this version may differ in some conventions, but will still be read by newer versions of the library.

Maybe this diagram will help us to figure out where the issue is occurring:

https://docs.google.com/drawings/d/1zh7PApJfA5WEarrPe48_nWd2Z2wECfF5xNUdTKhu2CI/edit?usp=sharing

<img src="https://docs.google.com/drawings/d/e/2PACX-1vSmAB9ODV4ansEW4-Jzt2OVo43tfHfatyuyq_wn4Cil9Ty3OflIZh2WELVWehHI_jL9t14JBcewb820/pub?w=3017&amp;h=1044">

**Comment by keller-mark** [comment]
From @mccalluc  on Slack:

> When I look at https://github.com/hubmapconsortium/azimuth-annotate/blob/main/docker/Dockerfile#L19, the anndata version doesn’t seem to be pinned… I’d suggest making the version explicit in the Dockerfile.

The [sprm-to-anndata](https://github.com/hubmapconsortium/portal-containers/blob/master/containers/sprm-to-anndata/context/requirements-freeze.txt) portal-container uses `anndata==0.7.1` and we have also written our JS tests using [fixtures](https://github.com/vitessce/vitessce/blob/main/src/loaders/fixtures/anndata/requirements.txt) produced by `anndata==0.7.1` in case that info is helpful.

**Comment by mccalluc** [comment]
Ok: I think we're all on the same page that the fix needs to happen in azimuth-annotate, so I've [filed a new issue there](https://github.com/hubmapconsortium/azimuth-annotate/issues/3), linking to the discussion here. No work to be done in portal-ui, so closing.
