### ISSUE TITLE
Clarify workspace deletion UI

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2848]
Workspaces can not be deleted with running jobs, so for now we're going to try stopping running jobs first.

Nils says
> Maybe give the user a warning that the workspace is active and if they still want to delete do a force delete?

Should there be a separate option to stop jobs on a workspace, separate from workspace deletion?

Also, the current UI is a bulk delete... Could it be changed to a per-dataset delete option? Fewer mouseclicks, closer correspondence between UI and API, don't need to work with partial success / partial failure.

**Comment by jpuerto-psc** [comment]
From an API perspective, I believe that these two functions should be kept separate.

Because of the AWS gateway, tacking this on to the workspace deletion requires additional asynchronous tasks to run (which always introduces potential for complexity) to avoid gateway timeouts. Not to mention that, although not present in the UI, the API has the ability to support multi-job workspaces. I wouldn't want to introduce the ability for a user to accidentally stop all of their jobs when trying to delete a workspace without understanding what they're really doing.

On the other hand, telling a job to stop, polling to ensure that the job is complete, and then deleting the workspace, is safer since it is synchronous and lets the user know exactly what is going on with their JupyterLab session.

**Comment by mccalluc** [comment]
Filed new issue for implementation. Closing.
