### ISSUE TITLE
agree-not-to-reidentify click-through

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#45]
On first visiting the site, users should be prompted to confirm that they will not attempt to reidentify donors. 

Blocking on:
- Ok to do this just on the client side, with a log-lived cookie?

Can come later:
- Exact wording.
- Design.

**Comment by ngehlenborg** [comment]
I think for people who do not have an account, we should handle this with a cookie. I am not sure right now at what point we need to display this. Maybe when they attempt to download a file?

Additionally, this also should be handled during account creation. @shirey @computationdoc: What do you think?

**Comment by computationdoc** [comment]
Well I only have the message here on my phone presently not the original thread, but Nils you seem to be suggesting a third way of tracking people - I think two should be enough if I understand correctly

In other words, to access things that are unrestricted open with no policy to restrict or track to any person or agent in the Internet universe don’t log in and no collection of identity 

Those activities that cannot fall in above log in - which identifies (even can be a non proven identity like Google Auth)

As you know, A cookie marks a device, not a person or agent, so we can in theory mark a device as having acknowledged something but I’m dubious that serves any legal purpose - and not clear how to collect cookie when the activity is solely API access - which is an essential approach (otherwise only HuBMAP can write web apps for HuBMAP data right? Surely we don’t want that?!)

Jonathan C. Silverstein, MD, MS, FACS, FACMI

**Comment by mccalluc** [comment]
@ngehlenborg or @computationdoc : Do either of you believe this (or something else in this space) is a requirement for the mid-May release? If so, can you provide a spec, or suggest some requirements?

(If not needed for mid-May, will it ever be needed?)

Assigning @tliaw512 now to implement, when/if there is something to implement.

**Comment by ngehlenborg** [comment]
This will still be needed. From our end, this should pop up when users click on a download link for a file. We can place a cookie that confirms that they have seen this. Cookie should expire after n weeks (value of n tbd).

**Comment by computationdoc** [comment]
Perhaps the below is the approach - I have to see precisely how this behaves but its a feature of Globus transfer to provide information to users regarding appropriate use of any endpoint - e.g. by downloading data from HuBMAP you agree to not re-identify patients…

**Comment by mccalluc** [comment]
Refined in #443. Closing this as duplicate.
