### ISSUE TITLE
Protocols.io log in required?

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#694]
## Feedback

__Submitter Name__: Ajay Pillai

__Submitter Email__: Pillai, Ajay (NIH/NHGRI) [E] <ajay.pillai3@nih.gov>

__Message__:
Main reason I am sharing this is because Ajay is saying that he has to log into protocols.io - I believe this is supposed to be public?  @ngehlenborg @computationdoc @shirey 

What was missing within the scoped list of features and data?
1 response
It is irritating that I have to login separately into protocols.io!

**Comment by ngehlenborg** [comment]
The issue here is a UX problem in the design of protocols.io. There is actually no need for registering or signing in, all you have to do is to click on the dark overlay and the login/registration prompt will disappear:

![stupid-protocols io-ux](https://user-images.githubusercontent.com/1216518/87168194-1c144a80-c29c-11ea-88f5-c2d154c3ef18.gif)

@computationdoc: is this something that you want to raise with protocols.io team? I understand their motivation, as a commercial entity they need to collect as much user information as possible, but I agree with Ajay that this is misleading and annoying.

**Comment by mccalluc** [comment]
It feels like this is entirely outside hubmap, so I'll close. If there is action on our side, clarify what that is and reopen?

**Comment by computationdoc** [comment]
@pecan88 Protocols.io sent apology and will put a dismiss button of some sort on their end, so that it doesn't appear that logon is required. Logon is certainly not required. Thanks all. Peter will follow up that this is resolved with protocols.io. I will leave the issue closed here.
