### ISSUE TITLE
Compress webpack bundle

### ISSUE THREAD

**Issue by john-conroy** [hubmapconsortium/portal-ui#711]
We should be compressing our bundles into a gzip. The change will require some nginx [configuration](http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html).

**Comment by mccalluc** [comment]
Not just configuration, but a new build of NGINX, if I'm reading it correctly. So I think the roadmap looks like:
- In the first stage, we build nginx with `--with-http_gzip_static_module`.
- In the second stage, our fork of [uwsgi-nginx-docker](https://github.com/tiangolo/uwsgi-nginx-docker/blob/master/docker-images/install-nginx-debian.sh) will reference our nginx build instead of using the debian package.
- In the third stage our fork of [uwsgi-nginx-flask-docker](https://github.com/tiangolo/uwsgi-nginx-flask-docker) adds flask to the previous layer.
- Then the stages we already have: webpack build, and
- run flask.

This scares me, a bit. I'd really like to find a prebuilt nginx with gzip, or better, an image that takes care of some of those first layers.

**Comment by john-conroy** [comment]
Looking at new resources, I think Brotli compression may be a better path than gzip.
