### ISSUE TITLE
Best way to expose uwsgi... if that's what we want to do?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#78]
Starting from [this PR](https://github.com/hubmapconsortium/portal-ui/pull/77#issuecomment-566129416), I wondered if we could expose uwsgi, so this container could be put behind the gateway nginx, but I'm not sure about the best roadmap for this. I (@mccalluc) can do a lot of the work, but I want to make sure it actually satisfies the needs of PSC before investing more time. Options:
- No work / keep nginx here, and keep this outside gateway, or something like that.
- Use a different base image that is just Flask + uWSGI.
- Expose uWSGI port. I think I know where the socket file is (see PR linked above): `unix:///tmp/uwsgi.sock`, and we could install [`socat`](https://serverfault.com/questions/517906/how-to-expose-a-unix-domain-socket-directly-over-tcp) and connect that socket to a port.

@yuanzhou : Perhaps talk with Bill and let me know the best way forward.

**Comment by yuanzhou** [comment]
We don't need to expose uwsgi, it's fine to have nginx/wusgi/flask in the same image. This way it's good for you local development. And for my work with deployment just like what I did earlier, the gateway's nginx handles the ssl and does a proxy to the portal-ui's nginx. This only thing we need to resolve is to make the hostname or backend URL configurable in the flask's `app.conf`. To avoid the mismatch URL from globus redirect. 

The reason why flask picks up the `portal-ui` as the hostname is because it's running in a container named `portal-ui` which is defined in the docker-compose file. So if we make the flask to read the base URL from configuration file, we can use it for deployment which redirects to 'https://portal.test.hubmapconsortium.org/'. On the local development environment, you can specify this as 'http://localhost:5000/'.

**Comment by mccalluc** [comment]
See also #89: Trying to debug the problem.

**Comment by mccalluc** [comment]
Moot. #89 is fixed.
