### ISSUE TITLE
Update sample hierarchy in provenance table

### ISSUE THREAD

**Issue by john-conroy** [hubmapconsortium/portal-ui#941]
The sample hierarchy is less constrained than we thought.

> No, organ only shows up in the list if the parent entity is a Donor.  That may be the only constraint that we have in place.

We will need to adopt the logic from the provenance graph.

**Comment by ngehlenborg** [comment]
Here is an example that is not displayed correctly in the provenance table but correctly displayed in the provenance graph (because the sequence is organ -> organ piece -> organ piece -> dataset): https://portal.hubmapconsortium.org/browse/sample/38980e9bcbf6a6bd9c6789ee4a45eea5

Provenance Table:
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/1216518/89213992-f7a64800-d593-11ea-84ee-2be6328de192.png">

Provenance Graph:
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/1216518/89214081-245a5f80-d594-11ea-89b9-f3489fe69b6a.png">

Here is a discussion about the (lack of constraints) in the sample hierarchy: https://hubmapconsortium.slack.com/archives/C011RF3NQ23/p1596061469439300

And here is a discussion about how the issue was initially discovered: https://hubmapconsortium.slack.com/archives/C011RF3NQ23/p1595875433352300?thread_ts=1595875433.352300

**Comment by john-conroy** [comment]
We presently won't be updating the provenance table. If we do it will be more of a redesign and new issues will be created.
